version: "3.0"

services:
  replica0:
    container_name: replica0
    hostname: replica0
    image: "replica:${TAG}"
    environment:
      - CLUSTER=1
      - ADDRESSES=10.20.20.10:3000,10.20.20.11:3000,10.20.20.12:3000
      - REPLICA_COUNT=3
      - REPLICA=0
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.10
  replica1:
    container_name: replica1
    hostname: replica1
    image: "replica:${TAG}"
    environment:
      - CLUSTER=1
      - ADDRESSES=10.20.20.10:3000,10.20.20.11:3000,10.20.20.12:3000
      - REPLICA_COUNT=3
      - REPLICA=1
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.11
  replica2:
    container_name: replica2
    hostname: replica2
    image: "replica:${TAG}"
    environment:
      - CLUSTER=1
      - ADDRESSES=10.20.20.10:3000,10.20.20.11:3000,10.20.20.12:3000
      - REPLICA_COUNT=3
      - REPLICA=2
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.12

  workload:
    container_name: workload
    hostname: workload
    image: "workload:${TAG}"
    environment:
      - CLUSTER=1
      - REPLICAS=10.20.20.10:3000,10.20.20.11:3000,10.20.20.12:3000
    networks:
      antithesis-net:
        ipv4_address: 10.20.20.100

# The subnet provided here is an example
# An alternate /24 can be used
networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
